### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hieplpvip** [hieplpvip/AsusSMC#16]
- [x] Add full support for Catalina

- [x] Change installation location of AsusSMCDaemon
Summary: On Catalina, /usr/bin is no longer available.

- [x] Add support for ROG keyboards.
Summary: Port [hid-asus.c](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-asus.c) and [rogauracore](https://github.com/wroberts/rogauracore) to macOS
Result: [AsusHIDDriver](https://github.com/hieplpvip/AsusSMC/blob/master/AsusHID/AsusHIDDriver.cpp) and [macrogaura](https://github.com/hieplpvip/macrogaura)

- [x] Fix bug on HID-based keyboard

- [ ] Support ACPI-based keyboard backlight found on some Vivobook Flip. Ref: https://github.com/hieplpvip/AsusSMC/issues/23
Summary: Keyboard backlight is controlled in method `_Q66` in ACPI. Looking at that method, it should work OOB, but it doesn't. **Need to investigate more**

- [x] Port WMI driver from Linux
Summary: Port [asus-wmi.c](https://github.com/torvalds/linux/blob/master/drivers/platform/x86/asus-wmi.c) to macOS

- [x] Fix `ALSC patch` for device with `ALSC` under `ATKD.WMNB`

**Comment by anonymous-writer** [comment]
Hi @hieplpvip , what do you meen with "Save ALS status across boot"?

**Comment by hieplpvip** [comment]
@anonymous-writer You can press Fn+A to toggle ALS.

**Comment by Ubsefor** [comment]
You can add `sudo mount -uw /` and `sudo mount -ur /` to mount system volume in rw and back in readonly, writing to /usr/bin generally requires root password anyway

**Comment by hieplpvip** [comment]
I do not prefer it. Installing to /usr/local/bin would be enough

**Comment by williambj1** [comment]
@hieplpvip 

Maybe this is useful https://github.com/acidanthera/VoodooInput/commit/3f6e60573b1317c6a3a18136cfbea9ee8eee6361

**Comment by MohammadtaghiFarkhondekar** [comment]
I hope fix problem in 10.15...
